language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '0.12'
  - '4.2'
  - '5.1'
cache:
  directories:
    - node_modules
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower@1.7.1 gulp@3.9.0 firebase-tools@2.2.0
  - bower i
script:
  - ./travis-runner.sh
env:
  global:
    - secure: "Mu/3070R3wApEyoq4Pw2WQswlaUDSAopNqfYZ7D46h/rqpS5EylpulnIVxki0LI9L0Kzvkn7INYs3BiuvPfV/iuy5ypypSWpaqMGP4x5iCD2D20Y12QRq6L5XV1gbQgYm+TkaU2U5EEHr+rxJ1JYhqmurhNtcfroUoOkN0Ej3XD8lG+19nbafsiNK2bmES/f/9a+3JsV4i0K+EPkXgMbN05lDqLJ0pfsBVcl94s4+GSBNQ4JEwowPaA1kRBTewIq8Qwm+p7YnlqZa9nImgK34Qeu43+EEriKBbaxdxoNerhs5flIQ0gJWsvpElZ9Hf6KJ4JJJcBaAdYn2SLYh5B0I2bZYDK3F3zqxvFUFnR/paxFXb0JN8wGFq/efbaYWttihFMcOq2Y23mz6s6xmHeK2TKvgul7pfC4anbJ8PGgByfiBBBfcTK6qWgN3W+p89IN/V2OWQm2gd2iil3HCoLNf4gHmmMVF9ikkocY6wVPj0bqeT8SNCwSUPgOwyQUpKlGroJyDpY53Y9qRrimdLVboSVpRfrJ9NbNwrguB/JWGEYaa3a8ZMoq57iV/1I67Trt/Rw4zo4bGzBU3hQGXeXHg8b4ulZpkYV3J0xrNzohAlf6LD6ktUSPOqmffag+f/r9SDkg5JYTbjVPgiM7Sh3lMW0tlwJwR5+MhYHr/Q1CLFo="
